version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/repo
    macos:
      xcode: 14.0.0
    steps:
      - checkout
      - run:
          name: Update Node
          command: "sudo npm install -g n && sudo n lts"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install --force
      - run:
          name: Install dpkg and fakeroot
          command: brew install dpkg fakeroot
      - run:
          name: Install rpm
          command: brew install rpm
      - run:
          name: Generate Builds
          command: npm run make-mac

      - store_artifacts:
          path: ~/repo/out/make
